apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-delete-base-secret.yaml
  - path: patch-delete-postgres-service.yaml
  - path: patch-delete-postgres-statefulset.yaml
  - path: patch-api-replicas.yaml
  - path: patch-api-service-loadbalancer.yaml
  - path: patch-configmap-rds.yaml
images:
  - name: oficina-mecanica-fiap
    newName: REPLACE_WITH_ECR_REPOSITORY_URL
    newTag: latest