[tool.poetry]
name = "oficina-mecanica-fiap"
version = "0.1.0"
description = "Projeto da Oficina Mecânica criado para o curso de Pós Graduação de Software Architecture solicitado pela FIAP para conclusão do curso"
authors = []
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.12"
uvicorn = { version = "^0.34.2", extras = ["standard"] }
python-jose = { version = "^3.5.0", extras = ["cryptography"] }
passlib = { version = "^1.7.4", extras = ["bcrypt"] }
python-multipart = "^0.0.20"
email-validator = "^2.2.0"
sqlalchemy = "^2.0.49"
psycopg = { version = "^3.2.3", extras = ["binary"] }

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
httpx = "^0.28.1"
bandit = "^1.8.3"
pip-audit = "^2.9.0"
reportlab = "^4.4.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=app/service_orders --cov=app/shared --cov=app/clients --cov=app/vehicles --cov=app/parts --cov=app/service_catalog --cov=app/auth --cov=app/system --cov-report=term-missing"

[tool.coverage.report]
fail_under = 80
skip_covered = true

[tool.bandit]
exclude_dirs = ["tests", ".venv", "reports"]
severity = ["LOW", "MEDIUM", "HIGH"]
skips = ["B101"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"