apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oficina-mecanica
resources:
  - locust-job.yaml
configMapGenerator:
  - name: oficina-mecanica-locust
    files:
      - locustfile.py=locustfile.py
