apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-api-service-nodeport.yaml
  - path: patch-api-replicas.yaml
images:
  - name: oficina-mecanica-fiap
    newName: phantosmia95/oficina-mecanica-fiap
    newTag: latest
