apiVersion: v1
kind: Service
metadata:
  name: oficina-mecanica-api
  namespace: oficina-mecanica
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30080
