apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: oficina-mecanica
spec:
  provider:
    aws:
      service: SecretsManager
      region: REPLACE_WITH_AWS_REGION
      auth:
        jwt:
          serviceAccountRef:
            name: oficina-mecanica-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oficina-mecanica-secret
  namespace: oficina-mecanica
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: oficina-mecanica-secret
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: REPLACE_WITH_APP_SECRET_NAME
        property: ADMIN_PASSWORD
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: REPLACE_WITH_APP_SECRET_NAME
        property: JWT_SECRET_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: REPLACE_WITH_APP_SECRET_NAME
        property: POSTGRES_PASSWORD
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: REPLACE_WITH_APP_SECRET_NAME
        property: SMTP_PASSWORD
