apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secret.yaml
  - ingress.yaml
  - service-account.yaml
patches:
  - path: patch-delete-base-secret.yaml
  - path: patch-delete-postgres.yaml
  - path: patch-api-service-account.yaml
  - path: patch-configmap-rds.yaml
images:
  - name: oficina-mecanica-fiap
    newName: REPLACE_WITH_ECR_REPOSITORY_URL
    newTag: latest
