apiVersion: v1
kind: Secret
metadata:
  name: oficina-mecanica-secret
  namespace: oficina-mecanica
type: Opaque
stringData:
  ADMIN_PASSWORD: Admin@123
  JWT_SECRET_KEY: change-me-in-production
  POSTGRES_PASSWORD: oficina
  SMTP_PASSWORD: ""
  NEW_RELIC_LICENSE_KEY: ""
